language: python
dist: xenial
python:
  - "3.7"
install:
  - - pipenv install --dev --ignore-pipfile --deploy
script: pytest

deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: script
  script: pipenv run python submit.py